// <auto-generated />
using System;
using AMRVI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMRVI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203152756_SeedDataPlants")]
    partial class SeedDataPlants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMRVI.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("StandardDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("ChecklistItems_RVI", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Emergency Stop",
                            ImagePath = "/images/checklist/injection/emergency-stop.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 1,
                            StandardDescription = "Pastikan tombol emergency stop berfungsi dengan baik dan mudah dijangkau"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Safety Light Curtain",
                            ImagePath = "/images/checklist/injection/safety-light-curtain.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 2,
                            StandardDescription = "Pastikan pergerakan Ejector & Mold berhenti saat light curtain aktif"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Safety Door",
                            ImagePath = "/images/checklist/injection/safety-door.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 3,
                            StandardDescription = "Pastikan pintu safety tertutup rapat dan interlock berfungsi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Hydraulic Pressure",
                            ImagePath = "/images/checklist/injection/hydraulic-pressure.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 4,
                            StandardDescription = "Cek tekanan hydraulic dalam range normal (150-200 bar)"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Heating System",
                            ImagePath = "/images/checklist/injection/heating-system.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 5,
                            StandardDescription = "Pastikan suhu barrel sesuai dengan setting point"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Cooling System",
                            ImagePath = "/images/checklist/injection/cooling-system.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 6,
                            StandardDescription = "Cek aliran air cooling dan suhu"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Mold Condition",
                            ImagePath = "/images/checklist/injection/mold-condition.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 7,
                            StandardDescription = "Pastikan mold bersih dan tidak ada kerusakan"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Ejector System",
                            ImagePath = "/images/checklist/injection/ejector-system.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 8,
                            StandardDescription = "Cek pergerakan ejector smooth dan tidak macet"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Hopper Dryer",
                            ImagePath = "/images/checklist/injection/hopper-dryer.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 9,
                            StandardDescription = "Pastikan material kering dan suhu dryer sesuai"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Robot Arm",
                            ImagePath = "/images/checklist/injection/robot-arm.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 10,
                            StandardDescription = "Cek pergerakan robot arm dan vacuum system"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Oil Level",
                            ImagePath = "/images/checklist/injection/oil-level.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 11,
                            StandardDescription = "Pastikan level oli hydraulic dalam batas normal"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Cleanliness",
                            ImagePath = "/images/checklist/injection/cleanliness.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 12,
                            StandardDescription = "Area mesin bersih dari oli, material, dan kotoran"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DetailName = "Control Panel",
                            ImagePath = "/images/checklist/injection/control-panel.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 13,
                            StandardDescription = "Pastikan display dan tombol kontrol berfungsi normal"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_BTR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("StandardDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("ChecklistItems_BTR");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_HOSE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("StandardDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("ChecklistItems_HOSE");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_MIXING", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("StandardDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("ChecklistItems_MIXING");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_MOLDED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("StandardDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("ChecklistItems_MOLDED");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Judgement")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("InspectionSessionId");

                    b.ToTable("InspectionResults_RVI", (string)null);
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult_BTR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Judgement")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("InspectionSessionId");

                    b.ToTable("InspectionResults_BTR");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult_HOSE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Judgement")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("InspectionSessionId");

                    b.ToTable("InspectionResults_HOSE");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult_MIXING", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Judgement")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("InspectionSessionId");

                    b.ToTable("InspectionResults_MIXING");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult_MOLDED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Judgement")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("InspectionSessionId");

                    b.ToTable("InspectionResults_MOLDED");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MachineNumberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineNumberId");

                    b.ToTable("InspectionSessions_RVI", (string)null);
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_BTR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MachineNumberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineNumberId");

                    b.ToTable("InspectionSessions_BTR");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_HOSE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MachineNumberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineNumberId");

                    b.ToTable("InspectionSessions_HOSE");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_MIXING", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MachineNumberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineNumberId");

                    b.ToTable("InspectionSessions_MIXING");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_MOLDED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MachineNumberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineNumberId");

                    b.ToTable("InspectionSessions_MOLDED");
                });

            modelBuilder.Entity("AMRVI.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Machines_RVI", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Injection Molding Machine",
                            IsActive = true,
                            Name = "MESIN INJECTION"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Press Machine",
                            IsActive = true,
                            Name = "MESIN PRESS"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "CNC Machine",
                            IsActive = true,
                            Name = "MESIN CNC"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineNumbers_RVI", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "Area A",
                            MachineId = 1,
                            Number = "1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "Area A",
                            MachineId = 1,
                            Number = "2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "Area B",
                            MachineId = 1,
                            Number = "3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "Area C",
                            MachineId = 2,
                            Number = "1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "Area C",
                            MachineId = 2,
                            Number = "2"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "Area D",
                            MachineId = 3,
                            Number = "1"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_BTR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineNumbers_BTR");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_HOSE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineNumbers_HOSE");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_MIXING", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineNumbers_MIXING");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_MOLDED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineNumbers_MOLDED");
                });

            modelBuilder.Entity("AMRVI.Models.Machine_BTR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Machines_BTR");
                });

            modelBuilder.Entity("AMRVI.Models.Machine_HOSE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Machines_HOSE");
                });

            modelBuilder.Entity("AMRVI.Models.Machine_MIXING", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Machines_MIXING");
                });

            modelBuilder.Entity("AMRVI.Models.Machine_MOLDED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Machines_MOLDED");
                });

            modelBuilder.Entity("AMRVI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users_RVI", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "admin@amrvi.com",
                            FullName = "Administrator",
                            IsActive = true,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Production",
                            Email = "supervisor@amrvi.com",
                            FullName = "Supervisor Production",
                            IsActive = true,
                            Password = "super123",
                            Role = "Supervisor",
                            Username = "supervisor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Production",
                            Email = "operator1@amrvi.com",
                            FullName = "Operator Mesin 1",
                            IsActive = true,
                            Password = "user123",
                            Role = "User",
                            Username = "operator1"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.User_BTR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users_BTR");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "admin.btr@amrvi.com",
                            FullName = "Admin BTR",
                            IsActive = true,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.User_HOSE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users_HOSE");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "admin.hose@amrvi.com",
                            FullName = "Admin HOSE",
                            IsActive = true,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.User_MIXING", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users_MIXING");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "admin.mixing@amrvi.com",
                            FullName = "Admin MIXING",
                            IsActive = true,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.User_MOLDED", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users_MOLDED");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "admin.molded@amrvi.com",
                            FullName = "Admin MOLDED",
                            IsActive = true,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem", b =>
                {
                    b.HasOne("AMRVI.Models.Machine", "Machine")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_BTR", b =>
                {
                    b.HasOne("AMRVI.Models.Machine_BTR", "Machine")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_HOSE", b =>
                {
                    b.HasOne("AMRVI.Models.Machine_HOSE", "Machine")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_MIXING", b =>
                {
                    b.HasOne("AMRVI.Models.Machine_MIXING", "Machine")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_MOLDED", b =>
                {
                    b.HasOne("AMRVI.Models.Machine_MOLDED", "Machine")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult", b =>
                {
                    b.HasOne("AMRVI.Models.ChecklistItem", "ChecklistItem")
                        .WithMany("InspectionResults")
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMRVI.Models.InspectionSession", "InspectionSession")
                        .WithMany("InspectionResults")
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("InspectionSession");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult_BTR", b =>
                {
                    b.HasOne("AMRVI.Models.ChecklistItem_BTR", "ChecklistItem")
                        .WithMany("InspectionResults")
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMRVI.Models.InspectionSession_BTR", "InspectionSession")
                        .WithMany("InspectionResults")
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("InspectionSession");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult_HOSE", b =>
                {
                    b.HasOne("AMRVI.Models.ChecklistItem_HOSE", "ChecklistItem")
                        .WithMany("InspectionResults")
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMRVI.Models.InspectionSession_HOSE", "InspectionSession")
                        .WithMany("InspectionResults")
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("InspectionSession");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult_MIXING", b =>
                {
                    b.HasOne("AMRVI.Models.ChecklistItem_MIXING", "ChecklistItem")
                        .WithMany("InspectionResults")
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMRVI.Models.InspectionSession_MIXING", "InspectionSession")
                        .WithMany("InspectionResults")
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("InspectionSession");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult_MOLDED", b =>
                {
                    b.HasOne("AMRVI.Models.ChecklistItem_MOLDED", "ChecklistItem")
                        .WithMany("InspectionResults")
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMRVI.Models.InspectionSession_MOLDED", "InspectionSession")
                        .WithMany("InspectionResults")
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("InspectionSession");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession", b =>
                {
                    b.HasOne("AMRVI.Models.MachineNumber", "MachineNumber")
                        .WithMany("InspectionSessions")
                        .HasForeignKey("MachineNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineNumber");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_BTR", b =>
                {
                    b.HasOne("AMRVI.Models.MachineNumber_BTR", "MachineNumber")
                        .WithMany("InspectionSessions")
                        .HasForeignKey("MachineNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineNumber");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_HOSE", b =>
                {
                    b.HasOne("AMRVI.Models.MachineNumber_HOSE", "MachineNumber")
                        .WithMany("InspectionSessions")
                        .HasForeignKey("MachineNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineNumber");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_MIXING", b =>
                {
                    b.HasOne("AMRVI.Models.MachineNumber_MIXING", "MachineNumber")
                        .WithMany("InspectionSessions")
                        .HasForeignKey("MachineNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineNumber");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_MOLDED", b =>
                {
                    b.HasOne("AMRVI.Models.MachineNumber_MOLDED", "MachineNumber")
                        .WithMany("InspectionSessions")
                        .HasForeignKey("MachineNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineNumber");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber", b =>
                {
                    b.HasOne("AMRVI.Models.Machine", "Machine")
                        .WithMany("MachineNumbers")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_BTR", b =>
                {
                    b.HasOne("AMRVI.Models.Machine_BTR", "Machine")
                        .WithMany("MachineNumbers")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_HOSE", b =>
                {
                    b.HasOne("AMRVI.Models.Machine_HOSE", "Machine")
                        .WithMany("MachineNumbers")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_MIXING", b =>
                {
                    b.HasOne("AMRVI.Models.Machine_MIXING", "Machine")
                        .WithMany("MachineNumbers")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_MOLDED", b =>
                {
                    b.HasOne("AMRVI.Models.Machine_MOLDED", "Machine")
                        .WithMany("MachineNumbers")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_BTR", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_HOSE", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_MIXING", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem_MOLDED", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_BTR", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_HOSE", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_MIXING", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession_MOLDED", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.Machine", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("MachineNumbers");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber", b =>
                {
                    b.Navigation("InspectionSessions");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_BTR", b =>
                {
                    b.Navigation("InspectionSessions");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_HOSE", b =>
                {
                    b.Navigation("InspectionSessions");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_MIXING", b =>
                {
                    b.Navigation("InspectionSessions");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber_MOLDED", b =>
                {
                    b.Navigation("InspectionSessions");
                });

            modelBuilder.Entity("AMRVI.Models.Machine_BTR", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("MachineNumbers");
                });

            modelBuilder.Entity("AMRVI.Models.Machine_HOSE", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("MachineNumbers");
                });

            modelBuilder.Entity("AMRVI.Models.Machine_MIXING", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("MachineNumbers");
                });

            modelBuilder.Entity("AMRVI.Models.Machine_MOLDED", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("MachineNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
