// <auto-generated />
using System;
using AMRVI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMRVI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMRVI.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("StandardDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "OrderNumber");

                    b.ToTable("ChecklistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5064),
                            DetailName = "Emergency Stop",
                            ImagePath = "/images/checklist/injection/emergency-stop.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 1,
                            StandardDescription = "Pastikan tombol emergency stop berfungsi dengan baik dan mudah dijangkau"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5067),
                            DetailName = "Safety Light Curtain",
                            ImagePath = "/images/checklist/injection/safety-light-curtain.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 2,
                            StandardDescription = "Pastikan pergerakan Ejector & Mold berhenti saat light curtain aktif"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5069),
                            DetailName = "Safety Door",
                            ImagePath = "/images/checklist/injection/safety-door.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 3,
                            StandardDescription = "Pastikan pintu safety tertutup rapat dan interlock berfungsi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5071),
                            DetailName = "Hydraulic Pressure",
                            ImagePath = "/images/checklist/injection/hydraulic-pressure.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 4,
                            StandardDescription = "Cek tekanan hydraulic dalam range normal (150-200 bar)"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5073),
                            DetailName = "Heating System",
                            ImagePath = "/images/checklist/injection/heating-system.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 5,
                            StandardDescription = "Pastikan suhu barrel sesuai dengan setting point"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5075),
                            DetailName = "Cooling System",
                            ImagePath = "/images/checklist/injection/cooling-system.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 6,
                            StandardDescription = "Cek aliran air cooling dan suhu"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5077),
                            DetailName = "Mold Condition",
                            ImagePath = "/images/checklist/injection/mold-condition.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 7,
                            StandardDescription = "Pastikan mold bersih dan tidak ada kerusakan"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5079),
                            DetailName = "Ejector System",
                            ImagePath = "/images/checklist/injection/ejector-system.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 8,
                            StandardDescription = "Cek pergerakan ejector smooth dan tidak macet"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5081),
                            DetailName = "Hopper Dryer",
                            ImagePath = "/images/checklist/injection/hopper-dryer.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 9,
                            StandardDescription = "Pastikan material kering dan suhu dryer sesuai"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5110),
                            DetailName = "Robot Arm",
                            ImagePath = "/images/checklist/injection/robot-arm.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 10,
                            StandardDescription = "Cek pergerakan robot arm dan vacuum system"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5112),
                            DetailName = "Oil Level",
                            ImagePath = "/images/checklist/injection/oil-level.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 11,
                            StandardDescription = "Pastikan level oli hydraulic dalam batas normal"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5114),
                            DetailName = "Cleanliness",
                            ImagePath = "/images/checklist/injection/cleanliness.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 12,
                            StandardDescription = "Area mesin bersih dari oli, material, dan kotoran"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5117),
                            DetailName = "Control Panel",
                            ImagePath = "/images/checklist/injection/control-panel.jpg",
                            IsActive = true,
                            MachineId = 1,
                            OrderNumber = 13,
                            StandardDescription = "Pastikan display dan tombol kontrol berfungsi normal"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Judgement")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("InspectionSessionId");

                    b.ToTable("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MachineNumberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspectionDate");

                    b.HasIndex("MachineNumberId");

                    b.ToTable("InspectionSessions");
                });

            modelBuilder.Entity("AMRVI.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(4873),
                            Description = "Injection Molding Machine",
                            IsActive = true,
                            Name = "MESIN INJECTION"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(4875),
                            Description = "Press Machine",
                            IsActive = true,
                            Name = "MESIN PRESS"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(4878),
                            Description = "CNC Machine",
                            IsActive = true,
                            Name = "MESIN CNC"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "Number");

                    b.ToTable("MachineNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5032),
                            IsActive = true,
                            Location = "Area A",
                            MachineId = 1,
                            Number = "1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5034),
                            IsActive = true,
                            Location = "Area A",
                            MachineId = 1,
                            Number = "2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5036),
                            IsActive = true,
                            Location = "Area B",
                            MachineId = 1,
                            Number = "3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5038),
                            IsActive = true,
                            Location = "Area C",
                            MachineId = 2,
                            Number = "1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5040),
                            IsActive = true,
                            Location = "Area C",
                            MachineId = 2,
                            Number = "2"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 22, 58, 492, DateTimeKind.Local).AddTicks(5042),
                            IsActive = true,
                            Location = "Area D",
                            MachineId = 3,
                            Number = "1"
                        });
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem", b =>
                {
                    b.HasOne("AMRVI.Models.Machine", "Machine")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionResult", b =>
                {
                    b.HasOne("AMRVI.Models.ChecklistItem", "ChecklistItem")
                        .WithMany("InspectionResults")
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AMRVI.Models.InspectionSession", "InspectionSession")
                        .WithMany("InspectionResults")
                        .HasForeignKey("InspectionSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("InspectionSession");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession", b =>
                {
                    b.HasOne("AMRVI.Models.MachineNumber", "MachineNumber")
                        .WithMany("InspectionSessions")
                        .HasForeignKey("MachineNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineNumber");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber", b =>
                {
                    b.HasOne("AMRVI.Models.Machine", "Machine")
                        .WithMany("MachineNumbers")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AMRVI.Models.ChecklistItem", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.InspectionSession", b =>
                {
                    b.Navigation("InspectionResults");
                });

            modelBuilder.Entity("AMRVI.Models.Machine", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("MachineNumbers");
                });

            modelBuilder.Entity("AMRVI.Models.MachineNumber", b =>
                {
                    b.Navigation("InspectionSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
